### ISSUE TITLE
Opfor vehicles

### ISSUE THREAD

**Issue by nuxem** [nuxem/Salvation.tanoa#5]
Opfor vehicles crashing when changed to Tanoan variants possibly due to bounty system calling specific vehicle classes

**Comment by ghost** [comment]
Not sure about bounty causing collision onlything real bounty related is /scripts/shared/kill_manager.sqf
see line 78 to  104


scripts/shared/fetch_params.sqf 
has the variables for bounties 


/scripts/shared/kill_manager.sqf
has the base code for bounties calling all Air or Tank classes this should include tanoan vehicles

**Comment by nuxem** [comment]
Moved topic of post to all enemy vehicles, marked as duplicate. keeping post for comment info.

**Comment by nuxem** [comment]
Possible solution is to use Classnames extensions and rewrite the entire table to use vehicles we want instead of defaults.
