### ISSUE TITLE
RQ-12 Raptor Helicopter Drone unable to be controlled

### ISSUE THREAD

**Issue by nuxem** [nuxem/Salvation.tanoa#8]
Needs to be added to UAVs array in classnames.sqf, no crew inside cannot be connected to

**Comment by ghost** [comment]
Will have to build a work around for tanoa UAV's as of 1.66+ they changed how the drones work unless we zeus control it with troops we wont be able to fly them

**Comment by nuxem** [comment]
Resolved, Typo error in UAV designation array, did not spawn UAV with crew because of this.

B_UAV_03_F ---> B_T_UAV_03_F
